"""CL-12: emit provenance_manifest.json from the serving code path.

Platform-side per ADR-0009. Instantiates FraudScorer.from_pinned_artifacts()
so the manifest is generated by the SAME code the service runs -- no second
source of truth (D-06 class). Adds git SHA + build timestamp for CI traceability.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from verticals.fraud.serving.scorer import FraudScorer  # noqa: E402


def git_sha() -> str:
    out = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    )
    return out.stdout.strip()


def main() -> None:
    scorer = FraudScorer.from_pinned_artifacts()
    provenance = scorer._provenance()
    manifest = {
        **provenance.model_dump(),
        "git_sha": git_sha(),
        "build_timestamp_utc": datetime.now(timezone.utc).isoformat(),
    }
    out_path = REPO_ROOT / "provenance_manifest.json"
    out_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
