"""CL-24 — identity snapshot of the GOVERNED audit store (DEC-0016).

Records row identities, not counts. WS-E 65 survived every count-based
expectation: "two `fixture-*` rows" was true before a battery run and
true after it, while the two rows were in fact different rows and the
store had been dropped and recreated in between. "These two rows" is
false after, immediately and visibly. The proof that the CL-24
separation holds is therefore a BEFORE and an AFTER section listing the
same identities under the same digest.

Non-elevated by construction: connects as `arcaai_app`, whose grant is
SELECT and INSERT and nothing wider (sql/governance_grants.sql). This
script never needs, and must never be given, the owner role — residue
cleanup is a separate operator-commanded act.

Run (from repo root, conda arcaai, Docker dev stack up):

    python scripts/governed_store_identity.py BEFORE           # dry run
    python scripts/governed_store_identity.py BEFORE --live    # writes

Dry-run default per the house rule for operator scripts: the read is
always performed and reported, and only the evidence write is withheld.
Exit: 0 snapshot taken; 1 a duplicate label or a DB failure; 2 usage.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import sys

from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url

# Mirrors scripts/rehash_sweep.py: same role, same dev default, and like
# that sweep this is a control over the governed store specifically.
GOVERNED_DSN = "postgresql+psycopg://arcaai_app:app_dev@localhost:5432/arcaai_audit"
GOVERNED_DB_NAME = "arcaai_audit"

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_EVIDENCE = (
    REPO_ROOT / "docs" / "governance" / "CL-24_governed-store-baseline_2026-08-12.md"
)

# Primary keys read from arcaai/platform/governance/models.py, not
# guessed: audit_run and audit_run_terminal key on correlation_id, and
# audit_event compounds correlation_id with sequence_number. A first cut
# guessed `run_id` and `event_id` and failed against the live schema.
QUERIES = {
    "corpus_version": "SELECT version_id::text FROM corpus_version ORDER BY 1",
    "audit_run": "SELECT correlation_id::text FROM audit_run ORDER BY 1",
    "audit_event": (
        "SELECT correlation_id::text || ':' || sequence_number::text "
        "FROM audit_event ORDER BY 1"
    ),
    "audit_run_terminal": (
        "SELECT correlation_id::text FROM audit_run_terminal ORDER BY 1"
    ),
}

HEADER = """# CL-24 — governed audit store, identity baseline

Evidence for the CL-24 isolation change ruled at DEC-0016. Each section
below is one read of the governed `arcaai_audit` database, taken as the
`arcaai_app` role (SELECT and INSERT only, per `sql/governance_grants.sql`)
and therefore without elevation.

**The claim under test is identity, not count.** WS-E 65 was found because
two `fixture-*` rows became two *different* `fixture-*` rows across a
battery run: a count-based expectation passed every time while the store
was being destroyed and recreated beneath it. The proof that the isolation
holds is that a section taken after a full `scripts\\test.cmd` run lists the
same identities, and carries the same digest, as the section taken before it.

Generated by `scripts/governed_store_identity.py`; regenerate by re-running
that script with a new label and `--live`.
"""


def snapshot(dsn: str) -> tuple[dict[str, list[str]], str]:
    """Read every identity, oldest-agnostic and ordered, plus a digest.

    The digest covers `table:identity` pairs in QUERIES order, which is
    stable because dict literal order is stable — the digest is a
    convenience for eyeballing two sections, and the identity lists
    remain the actual evidence.
    """
    database = make_url(dsn).database or "<no database in URL>"
    if database != GOVERNED_DB_NAME:
        raise SystemExit(
            f"refusing to snapshot {database!r}: this is evidence about the governed "
            f"store {GOVERNED_DB_NAME!r}, and a snapshot of any other database would "
            f"be filed under a claim it does not support. See DEC-0016."
        )
    engine = create_engine(dsn)
    digest = hashlib.sha256()
    tables: dict[str, list[str]] = {}
    try:
        with engine.connect() as conn:
            for table, sql in QUERIES.items():
                ids = [r[0] for r in conn.execute(text(sql)).all()]
                tables[table] = ids
                for identity in ids:
                    digest.update(f"{table}:{identity}".encode())
    finally:
        engine.dispose()
    return tables, digest.hexdigest()


def render(label: str, tables: dict[str, list[str]], digest: str) -> str:
    lines = [f"\n## {label}\n"]
    total = sum(len(ids) for ids in tables.values())
    lines.append(f"Rows: {total}. Identity digest (sha256): `{digest}`\n")
    for table, ids in tables.items():
        lines.append(f"\n### {label} — {table} ({len(ids)} row(s))\n")
        lines.append("```")
        lines.extend(ids if ids else ["(no rows)"])
        lines.append("```\n")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("label", help="section label, e.g. BEFORE or AFTER-BATTERY")
    parser.add_argument("--evidence", type=pathlib.Path, default=DEFAULT_EVIDENCE)
    parser.add_argument("--live", action="store_true", help="write the evidence file")
    args = parser.parse_args()

    tables, digest = snapshot(GOVERNED_DSN)
    section = render(args.label, tables, digest)

    existing = args.evidence.read_text(encoding="utf-8") if args.evidence.exists() else HEADER
    # A repeated label would append a second identically-titled section
    # and read as one. Silent accumulation under an unchanged-looking
    # heading is the shape of the very residue problem CL-24 fixes.
    if f"\n## {args.label}\n" in existing:
        print(
            f"governed_store_identity: STOP — {args.evidence} already carries a "
            f"section labelled {args.label!r}. Choose a new label; sections are "
            f"never silently replaced."
        )
        return 1

    for table, ids in tables.items():
        print(f"{args.label}: {table}: {len(ids)} row(s)")
    print(f"{args.label}: identity digest sha256 = {digest}")

    if not args.live:
        print(f"{args.label}: DRY RUN — not written. Re-run with --live to write "
              f"{args.evidence}.")
        return 0

    # LF endings explicitly: .gitattributes forces LF on .md and
    # check_docs.py enforces it; Python would otherwise write CRLF here.
    args.evidence.parent.mkdir(parents=True, exist_ok=True)
    with open(args.evidence, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(existing + section)
    print(f"{args.label}: written to {args.evidence}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
